### ISSUE TITLE
Review: Community Page

### ISSUE THREAD

**Issue by edwin-zheng** [virtual-manoa-coders/vmc-uILA#41]
## Overview

In this review we will be looking at the Community page and its associated files.

## Review Branch

[review-041](https://github.com/virtual-manoa-coders/vmc-uILA/tree/review-041)

## Files to review

(Please list the files to be reviewed here. It would be great to provide the URL to each file in the review branch.)

* [Community.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-041/app/imports/ui/pages/Community.jsx)
* [UserTransportation.js](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-041/app/imports/api/userData/UserTransportation.js)
* [TransportMethodPieChart.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-041/app/imports/ui/components/TransportMethodPieChart.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

3/2/2021 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by JiajunK** [comment]
Community.jsx: maybe instead of inline CSS we could split it into the dedicated CSS file. (line 166 to 180)
TransportMethodPieChart: line 84: probably not a good comment; line 24: remove reference of "stuff"

**Comment by edwin-zheng** [comment]
Community.jsx
- Design-05: Line 31, 33, 199, 207
- ESLINT-01: Line 66, 72, 73, 108

UserTransportion.js
- Design-05: Line 8, 10, 12
- METEOR-3: no methods

TransportMethodPieChart.jsx
- Design-05: Line 24, 84
- ESLINT-01: Line 2, 5

Overall
METEOR-01
METEOR-02

**Comment by s-rathyen** [comment]
Community.jsx
Design-05: L199, L207 - Change the comment so it doesn’t say “Stuff” documents
Design-01: L167, 173, 179 - style = {{ fontFamily: ‘Comfortaa’ }}, textAlign=‘center’ as=‘h2’ is repeated in each line; can possibly reduce code duplication using style.css

TransportMethodPieChart.jsx
Design-03: L116, 117 - Unused/commented out code?

**Comment by angcylau** [comment]
Community.jsx:
  L66: ESLINT-01: Use 'const'instead of 'let'
  L72: ESLINT-01: Use 'const'instead of 'let'
  L73: ESLINT-01: Use operator assignment
  L108: ESLINT-01: 'timeSpan' is assigned a value but never used
  L207: Design-05: Innappropriate comment

TransportMethodPieChart.jsx:
  L2: ESLINT-01: 'Header' is an unused import
  L5: ESLINT-01: 'moment' is an unused import
  L40: Design-05: Unnecessary comment
  L63: JS-07: Avoid console.logs
  L68: Design-08: 'result' variable is redundant
  L85: Desing-08: 'defaultPreset' variable is redundant

**Comment by bradenbetz** [comment]
TransportMethodPieChart.jsx

JS-07 console.log on line 63

Design-05 Unnecessary Comments lines 40, 42

Community.jsx

Design-05 can probably put the comments from lines 57-60 into a JSDoc

**Comment by patimapoochai** [comment]
Community.jsx:
L57-60: Design-04: remove multiple line comments
L14,25,33,45,82: Design-05: Remove unnecessary comment
L14-104: Design-09: Export these to uitilities
L10: React-06: Define in tracker

UserTransportation.js:
Meteor-03: Should this be wrapped in mongo class?


TransportationMethodPieChart.jsx:
L84: Design-05: Remove comment
L116-117,42: JS-07: remove console.log()
L7-22: React-06 Define in tracker

**Comment by christianjensenv** [comment]
Community.jsx
L66, L72: Const perfered
L34, L50, L94: Code can be shortened, no need for extra variables
Reduce size of table to make it more UI friendly

UserTransportation.jsx
Looks fine, maybe add specific comments

TransportMethodPieChart.jsx
L2:  Header unused
L5: Moment unused
L68: Redundant code 'result'

**Comment by tgabatin** [comment]
Community.jsx:
Line 14: DESIGN-05 Comment not necessary
Line 108: ESLINT-01 Unused timeSpan method

TransportMethodPieChart.jsx:
Line 2,5: ESLINT-01 unused imports
Line 63: JS-07 console.log present

**Comment by cammoore** [comment]
Add the review to the milestone so it is visible to the team.

Community.jsx

React-09: L13 should be a function since it has no state.

JS-08: replace /** with //

Design-09: L15, 24, 44 Think about exporting functions so they can be
used in other components.

React: L127, 167, 173, 179 Define a const style to use instead of
copies of the same style.

UserTransportation.jsx

Design: It would be nice to have a define, update, remove, publish,
and subscribe methods on this class. That way we can control what
changes in the collection.

TransportationMethodPieChart.jsx

Javascript: L40 Can we use an object with keys then use const result =
_.values(TransportMethods)? This would simplify the forEach body.

JS-08: comments
