### ISSUE TITLE
Review: Functions.jsx

### ISSUE THREAD

**Issue by edwin-zheng** [virtual-manoa-coders/vmc-uILA#75]
## Overview

In this review, we will be going over Functions.jsx to ensure it adheres to our coding standards.

## Review Branch

review-75

## Files to review

* [Functions.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/master/app/imports/ui/components/Visualization/Functions.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

4/12/2021 12 PM

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## Functions.jsx

Add '.' to /** comments.

L41 add userId parameter?

**Comment by edwin-zheng** [comment]
Arch-01: Directory Visualization is capitalized

ESLint-01: 
 - Errors: L20, L41, L75
 - Warnings: L32, L53, L110, L165, L201

**Comment by patimapoochai** [comment]
Design-01: L99-100, onwards: can probably be put into a single function

Meteor-04: Need to switch over to validated methods

**Comment by angcylau** [comment]
ESLINT-01:
L20, 41: Remove curly braces and 'return' in arrow function.

L32, 53, 110, 165, 201: 'CO2Reduced', 'fuelSavedVar', 'averageCO2Reduced', 'averageFuelSaved' variables are redundant.

L33, 205: Returned expression type string is not assignable to type number.

L75: Use assignment operator: result[existingIndex].fuelSaved += doc.fuelSaved;

L105, 113: Condition is always false since types 'UserTransportationTypeEnum' and 'string' have no overlap

Design-01:
L101-120, 155-175: Refactor to reduce duplication.

**Comment by bradenbetz** [comment]
ESLINT-01: 
Expected no linebreak before this expression. (implicit-arrow-linebreak)
Assignment can be replaced with operator assignment. (operator-assignment)
Expected this semicolon to be at the end of the previous line. (semi-style)

DESIGN-09:
Could be moved to a Utilities folder, since the functions in this folder are being used across the app.

**Comment by JiajunK** [comment]
Line-4-9: Probably delete these when done with proj
Line: 105-110: Since this appears twice (again in line 160-165) anyway we can condense it?
Line-179:  Missing summary for function

**Comment by tgabatin** [comment]
ESLint -01: 
Line 20

Design 01:
Line 101,120 Refractor

Design-09:
File system needs to be restructured, functions are being reused through the code
